Version 3 of plag_submission_utils
PlagEvalRus/plag_submissions_utils pull request #1
Opened 2017-12-25 12:35 UTC by bakarov

add suport for cross-language plagiarism essays

2017-12-25 15:29 UTC, dvzubarev requested changes

2017-12-25 15:29 UTC, dvzubarev commented on plag_submissions_utils/v3/runner.py
> +            chks.LexicalSimChecker(opts),
Проверки, начиная с chks.PRChecker  имеет смысл убрать,  потому что на данный момент там сравниваются предложения на разных языках.

2017-12-25 15:29 UTC, dvzubarev commented on requirements.txt
> +json
убрать лишнее

2017-12-25 15:29 UTC, dvzubarev commented on plag_submissions_utils/common/api_key.py
> +api_key = 'trnsl.1.1.20171220T093118Z.6de6eb902dca717b.a78183a397fc9ab7624e6fa01062eff2fa8d2f9c'
это безопасно комитить этот токен?)

2017-12-25 15:29 UTC, dvzubarev commented on plag_submissions_utils/common/checkers.py
> +                if chunk.get_translated_sents()[0].encode('utf-8') is self._trans.translate(' '.join(chunk.get_orig_sents()), translator=chunk.get_translator_type_str()):
get_translated_sents()[0] - Точно всегда будет одно предложение в ячейке?

2017-12-25 15:29 UTC, dvzubarev commented on plag_submissions_utils/common/checkers.py
> +            if chunk.get_mod_sents()[0].encode('utf-8') == self._trans.translate(chunk.get_orig_sents()[0],
get_mod_sents()[0] - Точно всегда будет одно предложение в ячейке?

2017-12-26 11:50 UTC, bakarov commented
add changes

2017-12-27 08:48 UTC, dvzubarev approved these changes

2017-12-27 08:48 UTC, merged