add check for cyrillic chars leak
PlagEvalRus/plag_submissions_utils pull request #4
Opened 2018-01-16 10:25 UTC by bakarov

2018-01-16 11:02 UTC, dvzubarev requested changes

2018-01-16 11:02 UTC, dvzubarev commented on plag_submissions_utils/common/checkers.py
> +                    "Модифицированное предложение содержит замены отдельных букв!",
Я бы добавил в текст ошибки найденное слово и букву, написанную латиницей.

2018-01-16 11:02 UTC, dvzubarev commented on plag_submissions_utils/common/checkers.py
> +        self._re = regex.compile(r"[ А-я][A-z][А-я ]")
Чтобы выделить слово и матчить случаи 'онn.', и не матчить, отдельные слова такие как: ' I ', может что-то вроде такого использовать: `\b([А-я]*([A-z])[А-я]+|[А-я]+([A-z])[А-я]*)\b`

2018-01-17 10:39 UTC, bakarov commented
changes were applied

2018-01-17 11:25 UTC, merged